Epo ops 3.2
FHG-IMW/epo-ops pull request #3
Opened 2017-06-23 12:30 UTC by telzul

version bump of epo ops api
update to running travis on current ruby versions
some minor changes

2017-06-23 14:43 UTC, tamaloa requested changes
Nice work.

Please add:
* Reference to compatible ruby versions to README (refer to travis.yml)
* minor version bump in preparation of new release

2017-06-23 14:43 UTC, tamaloa commented on .ruby-version
> +2.3.3
as the gem targets several rubies (see .travis.yml) we should not include a .ruby-version file.

2017-06-26 12:49 UTC, telzul commented on .ruby-version
> +2.3.3
yes, i removed the file and also referred to the .travis.yml file in readme

2017-06-26 13:26 UTC, tamaloa approved these changes

2017-06-26 13:26 UTC, tamaloa commented
Let's `rake release` it :)

2017-06-26 13:42 UTC, merged